---
atlas: # Required by table_clearing
  ubuntu: [libatlas-base-dev]
box2d-dev: # Override; the default package installs a static lib.
  ubuntu: [box2d]
  osx:
    homebrew: [box2d]
clang-format-3.8:
  ubuntu: [clang-format-3.8]
  osx:
    homebrew: [clang-format@3.8]
dart:
  ubuntu: [libdart6-all-dev]
  osx:
    homebrew: [dartsim/dart/dartsim6]
debsums: # Required by NASA packages.
  ubuntu: [debsums]
libconfig++: # Required by libbarrett
  ubuntu: [libconfig++-dev]
liblapacke:
  ubuntu: [liblapacke-dev]
gfortran: # Required by table_clearing
  ubuntu: [gfortran]
glpk:
  ubuntu: [libglpk-dev]
  osx:
    homebrew: [homebrew/science/glpk]
libblas-dev: # Required by table_clearing
  ubuntu: [libblas-dev]
liblapack-dev: # Required by table_clearing
  ubuntu: [liblapack-dev]
mpfi:
  ubuntu: [libmpfi-dev]
newmat:
  ubuntu: [libnewmat10-dev]
nlopt: # Override; ros-indigo-nlopt is too old for DART.
  ubuntu: [libnlopt-dev]
openrave:
  ubuntu: [pr-openrave]
libopenthreads:
  ubuntu: [libopenthreads-dev]
python-boto3:
  ubuntu:
    pip: [boto3]
  osx:
    pip: [boto3]
python-descartes:
  ubuntu:
    pip: [descartes]
  osx:
    pip: [descartes]
python-enum: # Override; python-enum is too old for or_trajopt.
  ubuntu:
    pip: [enum34]
  osx:
    pip: [enum34]
python-hashlib:
  ubuntu:
    pip: [hashlib]
  osx:
    pip: [hashlib]
python-protobuf: # Required by NASA packages.
  ubuntu: [python-protobuf]
python-trollius:
  ubuntu:
    pip: [trollius]
  osx:
    pip: [trollius]
zeromq: # Required by NASA packages.
  ubuntu: [libzmq-dev]
python-palettable:
  ubuntu:
    pip: [palettable]
  osx:
    pip: [palettable]
python-scipy: # Required by table_clearing
  ubuntu:
    pip: [scipy]
python-scikit-learn:
  ubuntu:
    pip: [scikit-learn]
